image: maven:3.8.4-jdk-17

stages:
  - build
  - deploy

cache:
  paths:
    - .m2/repository

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode --errors --fail-at-end"

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar

deploy-job:
  stage: deploy
  image: ruby:3.1
  script:
    - echo "Deploying application..."
    - railway login --token $RAILWAY_TOKEN  # Autentica en Railway con el token que configuraste
    - railway up  # Despliega la aplicaci√≥n en Railway
    - echo "Application successfully deployed."
  only:
    - main